title: "Markdown od podstaw"
author: "Mikołaj Rotnicki"
description: "Samodzielny kurs przygotowywania uporządkowanych dokumentów w Markdown"
lang: "pl-PL"
theme: minima
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
